### ISSUE TITLE
Add hidden files to .gitignore

### ISSUE THREAD

**Issue by SSaishruthi** [IBM/MAX-Skeleton#26]
Can we either add `.*` to ignore all hidden files or add just `.DS_store` to ignore DS_Store files?

**Comment by SSaishruthi** [comment]
@djalova @bdwyer2 
Any suggestion on this?

**Comment by bdwyer2** [comment]
We don't want to add `.*` because that would ignore `.dockerignore` but we should add `.DS_store` and other files used by IDEs.

**Comment by SSaishruthi** [comment]
Is `.dockerignore` the only file that we need to force add if we include `.*`?

**Comment by xuhdev** [comment]
`.gitignore`, `.travis.yml`

**Comment by SSaishruthi** [comment]
I thought of suggesting explicit include using `!` prefix. If there are many files, I am not sure if it makes sense.

**Comment by ajbozarth** [comment]
we have added `.DS_store` to gitignore on other max repos previously so we should just add it here. wildcard ignores are generally not good practice unless in a subdirectory (eg `tests`)

**Comment by SSaishruthi** [comment]
Ref: #29
